import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Dashboard Points THP",
  description: "Generated by create next app",
};

import SessionProviderWrapper from "./components/SessionProviderWrapper";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}> {/* Ajout de flex et flex-col */}
        <SessionProviderWrapper>
          <header>
            <Navbar />
          </header>
        <main className="flex-grow"> {/* Ajout de flex-grow pour occuper l'espace restant */}
          {children}
        </main>
        <footer>
          <Footer />
        </footer>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
